# Google Mobility Data

In [1]:
import pandas as pd

In [63]:
google2020=pd.read_csv("2020_US_Region_Mobility_Report.csv")
google2021=pd.read_csv("2021_US_Region_Mobility_Report.csv")
google2022=pd.read_csv("2022_US_Region_Mobility_Report.csv")

In [64]:
googleall=google2020.append(google2021, ignore_index=True)

In [65]:
googleall=googleall.append(google2022, ignore_index=True)

In [66]:
googleall.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [67]:
googleall = googleall.dropna(subset=['sub_region_2'])

In [68]:
googleall=googleall.reset_index(drop=True)

In [73]:
googleall.tail()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
1914092,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-03-08,NaN,NaN,NaN,NaN,-23.0,NaN
1914093,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-03-09,NaN,NaN,NaN,NaN,-28.0,NaN
1914094,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-03-10,NaN,NaN,NaN,NaN,-28.0,NaN
1914095,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-03-11,NaN,NaN,NaN,NaN,-20.0,NaN
1914096,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-03-14,NaN,NaN,NaN,NaN,-23.0,NaN

In [70]:
googleall[.index]

RangeIndex(start=0, stop=1914097, step=1)

In [74]:
googleall.to_csv('googlemobility_US.csv')

In [43]:
googleall.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-15,5.0,7.0,NaN,NaN,-4.0,NaN
1,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-16,0.0,1.0,-23.0,NaN,-4.0,NaN
2,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-17,8.0,0.0,NaN,NaN,-27.0,5.0
3,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-18,-2.0,0.0,NaN,NaN,2.0,0.0
4,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-19,-2.0,0.0,NaN,NaN,2.0,0.0

In [44]:
googleall.dtypes

country_region_code                                    object
country_region                                         object
sub_region_1                                           object
sub_region_2                                           object
metro_area                                            float64
iso_3166_2_code                                        object
census_fips_code                                      float64
place_id                                               object
date                                                   object
retail_and_recreation_percent_change_from_baseline    float64
grocery_and_pharmacy_percent_change_from_baseline     float64
parks_percent_change_from_baseline                    float64
transit_stations_percent_change_from_baseline         float64
workplaces_percent_change_from_baseline               float64
residential_percent_change_from_baseline              float64
dtype: object

In [46]:
googleall['date'] = pd.to_datetime(googleall['date'])

In [53]:
googleall['weekday'] = googleall['date'].dt.day_name()

In [51]:
googleall.shape

(1914097, 16)

In [56]:
google_monday=googleall[googleall['weekday']=='Monday']

In [57]:
google_monday.to_csv('googlemobility_US_monday.csv')

In [61]:
google_monday.tail()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,weekday
1914076,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-02-14,NaN,NaN,NaN,NaN,-21.0,NaN,Monday
1914081,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-02-21,NaN,NaN,NaN,NaN,-51.0,NaN,Monday
1914086,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-02-28,NaN,NaN,NaN,NaN,-27.0,NaN,Monday
1914091,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-03-07,NaN,NaN,NaN,NaN,-24.0,NaN,Monday
1914096,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-03-14,NaN,NaN,NaN,NaN,-23.0,NaN,Monday

In [62]:
google_monday['sub_region_1'].value_counts()

Texas             21515
Georgia           15465
Virginia          13650
Kentucky          11212
Missouri          10960
North Carolina    10555
Iowa              10194
Illinois          10064
Indiana            9871
Tennessee          9726
Ohio               9528
Minnesota          8657
Michigan           8505
Mississippi        7863
Wisconsin          7442
Arkansas           7417
Alabama            7159
Florida            7135
Oklahoma           7024
Pennsylvania       7003
New York           6626
Kansas             6530
Louisiana          6376
California         6057
Nebraska           5417
Colorado           4948
South Carolina     4925
West Virginia      4849
Idaho              3833
Washington         3792
Oregon             3648
South Dakota       3169
Montana            3113
New Mexico         3031
Maryland           2601
Utah               2557
New Jersey         2289
North Dakota       2240
Wyoming            2215
Maine              1727
Arizona            1629
Massachusetts      1518
Vermont            1400
Nevada             1306
Alaska             1095
New Hampshire      1089
Connecticut         872
Rhode Island        545
Hawaii              436
Delaware            327
Name: sub_region_1, dtype: int64