# Google Mobility Data

In [1]:
import pandas as pd

In [4]:
google2020=pd.read_csv("2020_US_Region_Mobility_Report.csv")
google2021=pd.read_csv("2021_US_Region_Mobility_Report.csv")
google2022=pd.read_csv("2022_US_Region_Mobility_Report.csv")

In [5]:
googleall=google2020.append(google2021, ignore_index=True)

In [6]:
googleall=googleall.append(google2022, ignore_index=True)

In [7]:
googleall.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [9]:
googleall = googleall.dropna(subset=['sub_region_2'])

In [11]:
googleall=googleall.reset_index(drop=True)

In [12]:
googleall.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-15,5.0,7.0,NaN,NaN,-4.0,NaN
1,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-16,0.0,1.0,-23.0,NaN,-4.0,NaN
2,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-17,8.0,0.0,NaN,NaN,-27.0,5.0
3,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-18,-2.0,0.0,NaN,NaN,2.0,0.0
4,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,ChIJg9z7ewWPjogRA_8QrB0va7o,2020-02-19,-2.0,0.0,NaN,NaN,2.0,0.0

In [14]:
googleall.shape

(1914097, 15)

In [13]:
googleall.to_csv('googlemobility_US.csv')

In [16]:
googleall.groupby(['sub_region_1','sub_region_2'])